### ISSUE TITLE
使用Jeasyopc库提示异常"Unable to register some item to group"

### ISSUE THREAD

**Issue by stonedong** [luoyan35714/OPC_Client#8]
使用KingVIew做opc server，调用Jeasyopc库尝试读取点位数据，调用jopc.registerGroups()时会报异常
Exception in thread "main" javafish.clients.opc.exception.UnableAddItemException: Unable to register some item to group. 
	at javafish.clients.opc.JOpc.registerGroups(JOpc.java:296)
	at com.freud.opc.jeasyopc.JeasyopcTest06.main(JeasyopcTest06.java:36)
请问一下，是咋回事呢？

**Comment by luoyan35714** [comment]
没使用过KingView，我之前都是用的MatrikonOPCSimulation
